// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = String(import.meta.env.VITE_SUPABASE_URL || '').trim();
const SUPABASE_PUBLISHABLE_KEY = String(
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || ''
).trim();

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error(
    '[Supabase] Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY.'
  );
}

const safeStorage: Storage = {
  getItem: (key: string) => {
    try {
      return localStorage.getItem(key);
    } catch {
      console.warn('[SafeStorage] getItem failed for', key);
      return null;
    }
  },
  setItem: (key: string, value: string) => {
    try {
      localStorage.setItem(key, value);
    } catch {
      console.warn('[SafeStorage] setItem failed for', key);
    }
  },
  removeItem: (key: string) => {
    try {
      localStorage.removeItem(key);
    } catch {
      console.warn('[SafeStorage] removeItem failed for', key);
    }
  },
  get length() {
    try {
      return localStorage.length;
    } catch {
      return 0;
    }
  },
  clear: () => {
    try {
      localStorage.clear();
    } catch {
      console.warn('[SafeStorage] clear failed');
    }
  },
  key: (index: number) => {
    try {
      return localStorage.key(index);
    } catch {
      return null;
    }
  },
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://invalid.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'invalid-publishable-key',
  {
    auth: {
      storage: safeStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);

// Check if Supabase is properly configured
export const isSupabaseConfigured = Boolean(
  SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY
);
